# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f6f91be268c380ac872e6b48b0afcce012451b79d59ab113b16c83b55a8ee8af1a437d744db2a7561287a90cb3afa6bc4a54863792dcc4325ea0cf6e201167f

test:
  secret_key_base: dcc7be1e634f58ceef5435766fab2d79ac680142255aacb50df526d57e78b127189ef37a73579f309ae9c003311c46f98086340cedc29c6e42af93b90a607177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
